name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        components: clippy, rustfmt
        override: true
        toolchain: stable

    - uses: Swatinem/rust-cache@v1

    - run: cargo update --locked --package boilerplate

    - run: |
        cargo test --workspace
        cargo test --workspace --features axum

    - run: cargo clippy --workspace

    - run: cargo fmt --workspace -- --check

    - if: ${{ matrix.os != 'windows-latest' }}
      run: |
        brew install ripgrep
        ./bin/forbid
